DROP TABLE IF EXISTS dbo.Island;
DROP TABLE IF EXISTS dbo.PlayerStatistics;
DROP TABLE IF EXISTS dbo.Ship;
DROP TABLE IF EXISTS dbo.VisitedPoints;
DROP TABLE IF EXISTS dbo.Game;
DROP TABLE IF EXISTS dbo.Lobby_User;
DROP TABLE IF EXISTS dbo.Lobby;
DROP TABLE IF EXISTS dbo.Token;
DROP TABLE IF EXISTS dbo.User;

drop schema dbo;